'use client';
import {useEffect,useState} from 'react';
import {heroImages,siteFont} from '@/lib/appearance';
import type {Content,Lang,Campaign} from '@/lib/model';
import {ArrowUpLeft,ArrowUpRight,ArrowDown,Plus,Globe,MessageCircle,MoveUpRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
export default function Portfolio({content,mode,id}:{content:Content;mode:'home'|'work'|'campaign'|'service';id?:string}){
 const [lang,setLang]=useState<Lang>('ar');const [lightbox,setLightbox]=useState<number|null>(null);const [filter,setFilter]=useState('all');
 useEffect(()=>{const l=new URLSearchParams(location.search).get('lang')==='en'?'en':'ar';setLang(l)},[]);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr'},[lang]);
 const t=(ar:string,en:string)=>lang==='ar'?ar:en;const href=(p:string)=>p+'?lang='+lang;const Arrow=lang==='ar'?ArrowUpLeft:ArrowUpRight;
 const campaign=content.campaigns.find(c=>c.id===id);const category=content.categories.find(c=>c.id===id);const featured=content.campaigns.find(c=>c.featured)||content.campaigns[0];
 const works=content.campaigns.filter(c=>mode==='service'?c.categoryId===id:filter==='all'||c.categoryId===filter);
 const heroCampaign=content.settings.heroCampaignId===undefined?featured:content.campaigns.find(c=>c.id===content.settings.heroCampaignId);
 const wa='https://wa.me/'+content.settings.whatsapp;
 function toggle(){const l=lang==='ar'?'en':'ar';setLang(l);const u=new URL(location.href);u.searchParams.set('lang',l);history.replaceState(null,'',u)}
 function Card({c}:{c:Campaign}){return <a className="project-card" href={href('/campaigns/'+c.id)}><div className="project-picture"><img src={c.cover} alt={c.title[lang]} loading="lazy"/><span className="round-link"><Arrow size={23}/></span></div><div className="project-caption"><div><p className="eyebrow">{content.categories.find(s=>s.id===c.categoryId)?.name[lang]}</p><h3>{c.client[lang]}</h3></div><span>{t('شاهد الكامبين','View campaign')}</span></div></a>}
 return <div className="site" style={{fontFamily:siteFont(content.settings.fontAr,content.settings.fontEn)}} dir={lang==='ar'?'rtl':'ltr'}><a href="#main" className="skip">{t('انتقل للمحتوى','Skip to content')}</a>
 <header className="header"><a className="brand" href={href('/')} aria-label="ASIA AGENCY"><img src={content.settings.logo} alt="ASIA"/><div>{content.settings.name}<small>CREATIVE & DIGITAL AGENCY</small></div></a><nav aria-label={t('القائمة الرئيسية','Main navigation')}><a href={href('/work')}>{t('أعمالنا','Our work')}</a><a href={href('/')+'#services'}>{t('خدماتنا','Services')}</a><a href="#contact">{t('تواصل معنا','Contact')}</a></nav><button className="language" onClick={toggle}><Globe size={17}/>{t('English','العربية')}</button></header>
 <main id="main">
 {mode==='home'&&<><section className="hero"><div className="hero-copy"><div className="eyebrow light"><span className="tiny-line"/> {t('آسيا أجينسي • تصميم وإبداع وتسويق','ASIA AGENCY • DESIGN, CREATE, CONNECT')}</div><h1>{t('أفكار تُرى.','Ideas seen.')}<br/><span>{t('علامات تُذكر.','Brands remembered.')}</span></h1><p>{content.settings.intro[lang]}</p><a className="pill cream" href={href('/work')}>{t('اكتشف أعمالنا','Explore our work')}<Arrow size={22}/></a><div className="hero-bottom"><span>STRATEGY / DESIGN / CONTENT</span><ArrowDown size={19}/></div></div><a className="hero-art" href={href(heroCampaign?'/campaigns/'+heroCampaign.id:'/work')} aria-label={t('استكشف الأعمال','Explore our work')}><div className="art-label">{heroCampaign?'SELECTED PROJECT — '+heroCampaign.client.en.toUpperCase():'ASIA AGENCY — SELECTED WORK'}</div><div className="art-stack">{heroImages(content).map((src,i)=><img key={i} className={'stack-'+i} src={src} alt={t('عمل مختار من آسيا ','Selected ASIA artwork ')+(i+1)}/>)}</div><div className="art-bottom"><span>{heroCampaign?.client[lang]||t('أعمال آسيا','ASIA projects')}</span><span>{t('اكتشف الأعمال','Explore the work')} <Arrow size={19}/></span></div></a></section><div className="ribbon" dir="ltr"><span>BRANDING</span><Plus/><span>SOCIAL MEDIA</span><Plus/><span>CONTENT</span><Plus/><span>DIGITAL MARKETING</span><Plus/><span>ASIA AGENCY</span></div><section className="section selected"><div className="section-heading"><div><p className="eyebrow">01 / {t('معرض الأعمال','SELECTED WORK')}</p><h2>{t('شغلنا يتكلم.','Let the work speak.')}</h2></div><a className="text-link" href={href('/work')}>{t('كل الأعمال','All projects')}<Arrow size={21}/></a></div><div className="projects">{content.campaigns.filter(c=>c.featured).map(c=><Card key={c.id} c={c}/>)}{!content.campaigns.some(c=>c.featured)&&content.campaigns.slice(0,1).map(c=><Card key={c.id} c={c}/>)}</div></section><section id="services" className="section services"><div className="section-heading"><div><p className="eyebrow">02 / {t('خدماتنا','WHAT WE DO')}</p><h2>{t('من أول فكرة،','From the first idea,')}<br/>{t('لآخر تفصيلة.','to the final detail.')}</h2></div><p>{t('كل ما تحتاجه علامتك لتظهر بشخصيتها، وتتواصل مع جمهورها.','Everything your brand needs to show its personality and connect with its audience.')}</p></div><div className="service-list">{content.categories.map((c,i)=><a key={c.id} href={href('/services/'+c.id)}><span className="service-number">{String(i+1).padStart(2,'0')}</span><h3>{c.name[lang]}</h3><p>{c.description[lang]}</p><Arrow size={28}/></a>)}</div></section></>}
 {(mode==='work'||mode==='service')&&<section className="section work-page"><p className="eyebrow">ASIA / {t('معرض الأعمال','PORTFOLIO')}</p><h1>{mode==='service'?category?.name[lang]:t('كل فكرة، حكاية.','Every idea has a story.')}</h1><p className="lead">{mode==='service'?category?.description[lang]:t('تصفّح الكامبينات، واكتشف التفاصيل وراء كل مشروع.','Explore our campaigns and the details behind each project.')}</p>{mode==='work'&&<div className="filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>{t('الكل','All')}</button>{content.categories.map(c=><button className={filter===c.id?'active':''} key={c.id} onClick={()=>setFilter(c.id)}>{c.name[lang]}</button>)}</div>}<div className="projects">{works.map(c=><Card key={c.id} c={c}/>)}</div>{!works.length&&<Empty className="empty"><EmptyHeader><EmptyTitle>{t('الأعمال هنا قريبًا','Projects coming soon')}</EmptyTitle><EmptyDescription>{t('تواصل معنا لمعرفة المزيد عن هذه الخدمة.','Get in touch to learn more about this service.')}</EmptyDescription></EmptyHeader><a className="pill" href={wa}>{t('تواصل واتساب','Chat on WhatsApp')}<Arrow size={20}/></a></Empty>}</section>}
 {mode==='campaign'&&campaign&&<><section className="section campaign-intro"><a className="text-link" href={href('/work')}>{t('كل الأعمال','All projects')}</a><div className="campaign-heading"><div><p className="eyebrow">{content.categories.find(c=>c.id===campaign.categoryId)?.name[lang]}</p><h1>{campaign.client[lang]}</h1><h2>{campaign.title[lang]}</h2></div><p className="lead">{campaign.description[lang]}</p></div></section><div className="campaign-cover"><img src={campaign.cover} alt={campaign.title[lang]}/></div><section className="section campaign-gallery"><div className="section-heading"><h2>{t('تفاصيل الكامبين','Inside the campaign')}</h2><span>{campaign.media.length} {t('أعمال','artworks')}</span></div><div className="gallery">{campaign.media.map((m,i)=>m.type==='video'?<video key={m.url+i} src={m.url} controls playsInline preload="metadata" aria-label={m.alt[lang]}/>:<button key={m.url+i} onClick={()=>setLightbox(i)} aria-label={t('تكبير: ','Enlarge: ')+m.alt[lang]}><img src={m.url} alt={m.alt[lang]} loading="lazy"/><span><Plus size={20}/></span></button>)}</div></section><Dialog open={lightbox!==null} onOpenChange={open=>!open&&setLightbox(null)}><DialogContent className="lightbox"><DialogTitle className="sr-only">{campaign.title[lang]}</DialogTitle><DialogDescription className="sr-only">{t('عرض التصميم بالحجم الكامل','Full-size artwork')}</DialogDescription>{lightbox!==null&&<><img src={campaign.media[lightbox].url} alt={campaign.media[lightbox].alt[lang]}/><div className="lightbox-nav"><button onClick={()=>{let n=(lightbox-1+campaign.media.length)%campaign.media.length;while(campaign.media[n].type!=='image')n=(n-1+campaign.media.length)%campaign.media.length;setLightbox(n)}}>{t('السابق','Previous')}</button><span>{lightbox+1} / {campaign.media.length}</span><button onClick={()=>{let n=(lightbox+1)%campaign.media.length;while(campaign.media[n].type!=='image')n=(n+1)%campaign.media.length;setLightbox(n)}}>{t('التالي','Next')}</button></div></>}</DialogContent></Dialog></>}
 </main><footer id="contact"><div className="contact-top"><div><p className="eyebrow light">{t('عندك فكرة؟ خلينا نبدأ.','HAVE A PROJECT IN MIND?')}</p><h2>{t('الدور على علامتك.','Your brand is next.')}</h2></div><a className="pill cream" href={wa} target="_blank" rel="noreferrer">{t('ابدأ مشروعك معانا','Let’s create together')}<Arrow size={24}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {content.settings.name}</span><a href={wa} dir="ltr">+{content.settings.whatsapp}</a><div>{content.settings.instagram&&<a href={content.settings.instagram}>Instagram</a>}{content.settings.facebook&&<a href={content.settings.facebook}>Facebook</a>}<a href="/admin">{t('إدارة الموقع','Site admin')}</a></div><button className="language" onClick={toggle}>{t('English','العربية')}<Globe size={16}/></button></div></footer><a className="whatsapp-float" href={wa} target="_blank" rel="noreferrer" aria-label="WhatsApp"><MessageCircle size={27}/></a></div>
}
