import type {Content} from "./model";
export const seed:Content={settings:{name:"ASIA AGENCY",intro:{ar:"نحوّل أفكارك إلى هوية واضحة، ومحتوى يلفت النظر، وحضور يليق بعلامتك.",en:"We turn ideas into distinctive identities, compelling content and a presence your brand deserves."},whatsapp:"201143142791",instagram:"",facebook:"",logo:"/work/IMG_0154.jpeg"},categories:[
{id:"social",name:{ar:"تصميمات السوشيال ميديا",en:"Social media design"},description:{ar:"كامبينات مترابطة وتصميمات توصل رسالتك من أول نظرة.",en:"Cohesive campaigns and visuals that make your message instantly clear."}},
{id:"branding",name:{ar:"البراندنج والهويات البصرية",en:"Branding & identity"},description:{ar:"شعارات وهويات تعبّر عن شخصية علامتك.",en:"Logos and visual identities built around your brand’s personality."}},
{id:"video",name:{ar:"التصوير والريلز والمونتاج",en:"Photography & film"},description:{ar:"تصوير ومحتوى متحرك يحكي قصتك.",en:"Photography, reels and editing that tell your story."}},
{id:"print",name:{ar:"المطبوعات والتغليف",en:"Print & packaging"},description:{ar:"تصميم يمتد من الشاشة إلى كل تفصيلة في منتجك.",en:"Design that extends beyond the screen into every brand touchpoint."}},
{id:"content",name:{ar:"إدارة السوشيال وكتابة المحتوى",en:"Social management & copy"},description:{ar:"أفكار وكتابة ونشر بصوت متسق مع علامتك.",en:"Ideas, copy and publishing with a consistent brand voice."}},
{id:"ads",name:{ar:"الإعلانات الممولة",en:"Paid advertising"},description:{ar:"تخطيط وإدارة الحملات للوصول إلى جمهورك.",en:"Campaign planning and management to reach your audience."}}
],campaigns:[{id:"marooo-pizza",title:{ar:"مارو… لكل وقت ومزاج",en:"Marooo. Every mood, every moment."},client:{ar:"بيتزا مارو",en:"Marooo Pizza"},description:{ar:"كامبين سوشيال ميديا يجمع بين أفكار بصرية مباشرة وصور شهية؛ يربط بيتزا مارو بمواقف يومية ومزاج مختلف، مع الحفاظ على حضور واضح للمنتج وهوية مترابطة.",en:"A social campaign pairing playful visual concepts with appetising product imagery. Each design connects Marooo Pizza to everyday moments, with the product at the heart of a cohesive identity."},categoryId:"social",cover:"/work/IMG_0061.jpeg",published:true,featured:true,media:["0060","0063","0066","0064","0068","0069","0067"].map((n,i)=>({url:"/work/IMG_"+n+".jpeg",type:"image" as const,alt:{ar:"تصميم "+(i+1)+" من كامبين بيتزا مارو",en:"Marooo Pizza campaign artwork "+(i+1)}}))}]};
